	<footer class="footer">
        <div class="footer-column">
            <img src="assets/images/logo.png" alt="SwinBalls logo" class="footer-logo" />
        </div>

        <div class="footer-column">
            <h4>SwinBalls</h4>
            <p>A Humble NFT Football Cards Marketplace</p>
        </div>

        <div class="footer-link footer-column">
            <a href="index.php" class="footer-link-item">Home</a>
            <a href="market.php" class="footer-link-item">Market</a>
            <a href="account.php" class="footer-link-item">Account</a>
        </div>

        <div class="footer-social footer-column">
            <a href="#" class="footer-social-item">
                <img src="assets/images/twitter.png" alt="Twitter Icon" />
            </a>
            <a href="#" class="footer-social-item">
				<img src="assets/images/youtube.png" alt="YouTube Icon" />
			</a>
			<a href="#" class="footer-social-item">
				<img src="assets/images/facebook.png" alt="Facebook Icon" />
			</a>
			<a href="#" class="footer-social-item">
				<img src="assets/images/instagram.png" alt="Instagram Icon" />
			</a>
        </div>
    </footer>