    <meta charset="UTF-8">
    <meta name="description" content="SwinBalls" />
    <meta name="keywords" content="HTML, CSS, PHP, MySQL" />
    <meta name="author" content="Regular People"  />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"  />
    <link href="assets/styles/style.css" rel="stylesheet"  />
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700" rel="stylesheet"  />
    <script src="https://kit.fontawesome.com/2d4d23f170.js" crossorigin="anonymous"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <title><?php echo $page_title; ?></title>