	<header id="nav-menu">
        <div class="container">
            <div class="nav-left">
                <a class="logo" href="index.php">
                    <img src="assets/images/logo.png" width="35" height="35" alt="Inc Logo" />
                </a>
                <nav class="menu">
                    <ul class="menu-bar">
                        <li><a class="nav-link" href="index.php">Home</a></li>
                        <li><a class="nav-link" href="market.php">Market</a></li>
                        <li><a class="nav-link" href="account.php">Account</a></li>
						<li><a class="nav-link" href="NFT_upload.php">Upload NFT</a></li>
                    </ul>
                </nav>
            </div>

            <div class="nav-right">
                <div class="right-container">
					<div class="balance">
						<img class="balance-icon" src="assets/images/coins.png" width="24" height="24" alt="Balance" />
						<a class="nav-link" href="account.php#addbalance">Buy Swincoin</a>
					</div>
                </div>

                <button id="hamburger" >
                    <img src="assets/images/hamburger.png" width="24" height="24" alt="Hamburger" />
                </button>
            </div>
        </div>
    </header>